using SolanaMusicApi.Application.Services.BaseService;
using SolanaMusicApi.Domain.Entities.Subscription;

namespace SolanaMusicApi.Application.Services.SubscriptionServices.SubscriptionPlanCurrencyService;

public interface ISubscriptionPlanCurrencyService : IBaseService<SubscriptionPlanCurrency>;
