using SolanaMusicApi.Domain.Entities.Performer;
using SolanaMusicApi.Infrastructure.Repositories.BaseRepository;

namespace SolanaMusicApi.Infrastructure.Repositories.ArtistRepositories.ArtistApplicationRepository;

public interface IArtistApplicationRepository : IBaseRepository<ArtistApplication>;